# Generated by Django 5.0.6 on 2024-05-20 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
        ('asignaturas', '0002_asignatura_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='asignatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asignaturas.asignatura'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='contacto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
