# Generated by Django 5.0.6 on 2024-05-19 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaturas', '0001_initial'),
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignaturas.asignatura'),
        ),
        migrations.DeleteModel(
            name='Asignatura',
        ),
    ]
