# Generated by Django 5.0.6 on 2024-05-19 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
        ('notas', '0002_alter_nota_asignatura_delete_asignatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno'),
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
    ]
