# Generated by Django 5.0.6 on 2024-05-20 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaturas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='descripcion',
            field=models.CharField(default='este es el campo para una descripcion general', max_length=500),
            preserve_default=False,
        ),
    ]
